### ISSUE TITLE
addEventListener 는 매우 중요함

### ISSUE THREAD

**Issue by youngminyu** [nubletea/portfolio#1]
DOM 컨트롤의 시작은 addEventListener 임.
그래서 간단하지만 유용한 팁(스크립트 코드 상단 수정)을 넣어봤음.

그밖에도 수정할 수 있는것들이 많아 보이지만 지금 모두 다하기보다는 다른 것도 만들어보면서 천천히 익히셈.

결론적으로 대단히 잘만들었음.

**Comment by nubletea** [comment]
감사합니다.
